language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    secure: aIHUgfUxCKKxUACKdlJczSe+H04PzVbBfgfh9WP7FBFslZ/Z+EUPTZaAr4u3IOTttM45t6xHVICu8a801JDSt3Z6gFfc6m+w0xv/3iGzdZT2c9dSr39BLvse8/pGjhB+NnfgRsosluuKEsiMjGyhiY6cYfrnyAkBlW3iv7LwSGnF6pl3ZIKyYT5dT6sOFyzH7+QnBEeYBlfGaK337xkxnAI1BvI09oDB9JcwKUzVEzctScA/Q5MeuxnnLDS+VdgoATkduKxgjZrqyCmMREyu77zX1fx7JxpL//uJB+EyqWiqnXvn0CXUAxA8oidsVLFR6znCX9Y8lClk0jzMUmQqGVjVClFWCQyKIuZN7HJLkxzIYn6nWXI+Ky1oL54Of6qa26Mi9iYGfITRRBhKNcxVIBdACmCLNhsC7PXDUq6Ua15gXN5x2MgI7mK/LNGpZB1uBzQr7RU0RPXokQwVYK3Z7vJYV4pcO9m/8l2QMr2073Y1i3UMLMryjFopfEXtBKKkffiPtPc3ksZshVsFoDX2H71L+WaqZw05zPVhOMIARTi7vmlMJcz5RK6vajHHSRG/MlhLJab7YsRcTKydZTK8M9NaFZz0If5mYxLNhBTEleHOtRuOZpCldbvPNkmXpbIHyPavt7SOdZRjUYiQCQMLOjihfUxPOMauoqBD2tZ+XDM=
