language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    secure: jzJfReuuFsqLm0wugXP46VVIGcDg//JI8nLJVpCM2sXVzRIrn9WitePDKqLstMJrYC68L7DGkRi1cCUr3p1tYu56VgTb5Q1nANaePxJAkofuyqK4qwYAM0d7NXzYYMggiO2j/7gcQZW/p6aQP6AS94bz9TSWMEKtmY/SNZb0pKaL1gPlDGtS4DryTotu/hUzrZJ79dD27pfdNHcJjvQAR/a1jugpACcDBIi7VjHAIRZQknvaHTczBwE2JM49xlc/9LEqdW2JgiLnTpfOFCRaFOCoARCHQyX/TbLdL2KmIR+jxQUXziQ32M/xDE70dWsLYKPgRXeQindoTtNDj//OVxqg9lmeWXtON5deHbIplNyYTTwSrapvq7yAMXpCsC1r/doxZa39T7qGE2689FWGTU/KZ02Rc6FbDcSvUrQYfNx1O/kuRP/n3ZKHI+hh24azEJQaQqYtLd5n+FAECvd0Ovb7D/rlb9ODPzVX6QxPG7Agv6uq8a4dGVpDBV6A3Yp+JItHfhQMLyYY7VOktjtNE6Lqw0PbDH9QC6swq5vRNrFrIzx8DAvNNXQo5q52QpdY4pOvZNV/sc+UGPCSCF0nzukq74trAuo7Kh7HS3WpcqtJvwynEhFccb2OMkKXr5B833a5EtvLKXzuml6Om4fXxBpVREUZfE8b2bhAeYcQp14=
